import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { isAdmin } from "@/lib/admin";
import { sendEmail } from "@/lib/email";
import { checkRateLimit } from "@/lib/rate-limit";
import { logAction } from "@/lib/audit/log-action";
import { buildInvitationEmail } from "@/lib/email-templates/invitation";

export const dynamic = "force-dynamic";

const INVITE_TTL_DAYS = 30;

export async function POST(request: Request) {
  try {
    // ── Auth: only admins may send invitations ──
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user || !isAdmin(user.email)) {
      return NextResponse.json({ error: "Acces refuse" }, { status: 403 });
    }

    const rl = await checkRateLimit({
      userId: user.id,
      endpoint: "admin-invite",
      limit: 20,
      windowMinutes: 60,
    });
    if (!rl.ok) {
      return NextResponse.json(
        { error: "Trop de requêtes, réessayez plus tard" },
        { status: 429 }
      );
    }

    const body = await request.json().catch(() => null);
    if (!body || typeof body !== "object") {
      return NextResponse.json({ error: "Requete invalide" }, { status: 400 });
    }

    const email =
      typeof body.email === "string" ? body.email.trim().toLowerCase() : "";
    const organizationId =
      typeof body.organization_id === "string"
        ? body.organization_id.trim()
        : "";

    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return NextResponse.json({ error: "Email invalide" }, { status: 400 });
    }

    const admin = createAdminClient();

    // ── Resolve organization ──
    let orgId = organizationId;
    let orgName = typeof body.nom_societe === "string" ? body.nom_societe : "";
    let clientType =
      typeof body.client_type === "string" ? body.client_type : "social";

    if (orgId) {
      // Fetch org for the email template
      const { data: org } = await admin
        .from("organizations")
        .select("id, name, client_type")
        .eq("id", orgId)
        .single();

      if (!org) {
        return NextResponse.json(
          { error: "Organisation introuvable" },
          { status: 400 }
        );
      }
      orgName = org.name;
      clientType = org.client_type;
    } else {
      // Legacy path: create invitation with odoo_partner_id lookup
      const odooPartnerId = Number(body.odoo_partner_id);
      if (!Number.isFinite(odooPartnerId) || odooPartnerId <= 0) {
        return NextResponse.json(
          { error: "organization_id ou odoo_partner_id requis" },
          { status: 400 }
        );
      }

      // Find or fail on organization
      const { data: org } = await admin
        .from("organizations")
        .select("id, name, client_type")
        .eq("odoo_partner_id", odooPartnerId)
        .maybeSingle();

      if (!org) {
        return NextResponse.json(
          {
            error:
              "Aucune organisation trouvee pour cet Odoo Partner ID. Creez d'abord l'organisation.",
          },
          { status: 400 }
        );
      }
      orgId = org.id;
      orgName = org.name;
      clientType = org.client_type;
    }

    // ── Insert invitation (token is auto-generated by DB default) ──
    const expiresAt = new Date(
      Date.now() + INVITE_TTL_DAYS * 24 * 60 * 60 * 1000
    ).toISOString();

    const ALLOWED_CLIENT_TYPES = ["social", "agency", "dactylo"] as const;
    if (!ALLOWED_CLIENT_TYPES.includes(clientType as (typeof ALLOWED_CLIENT_TYPES)[number])) {
      return NextResponse.json(
        { error: "Invalid client_type" },
        { status: 400 }
      );
    }

    const { data: inserted, error: insertError } = await admin
      .from("invitations")
      .insert({
        email,
        organization_id: orgId,
        client_type: clientType,
        expires_at: expiresAt,
        created_by: user.id,
      })
      .select()
      .single();

    if (insertError || !inserted) {
      console.error("[admin/invite] insert failed:", insertError);
      return NextResponse.json(
        {
          error:
            insertError?.message ||
            "Erreur lors de la creation de l'invitation.",
        },
        { status: 500 }
      );
    }

    await logAction({
      userId: user.id,
      organizationId: orgId,
      action: "user.invite",
      resourceType: "invitation",
      resourceId: inserted.id,
      metadata: {
        email,
        client_type: clientType,
        organization_name: orgName,
      },
    });

    // Detect prior soft-deleted account for this email so the UI can warn
    // the admin (we keep auth.users; setup-account will reactivate it).
    const { data: previousClient } = await admin
      .from("portal_clients")
      .select(
        "deleted_at, organization_id, organizations(name)"
      )
      .ilike("email_bailleur", email)
      .not("deleted_at", "is", null)
      .order("deleted_at", { ascending: false })
      .limit(1)
      .maybeSingle();

    const softDeleteWarning =
      previousClient && previousClient.deleted_at
        ? {
            warning: "user_soft_deleted" as const,
            previous_org_name:
              previousClient.organizations &&
              typeof previousClient.organizations === "object" &&
              !Array.isArray(previousClient.organizations)
                ? (previousClient.organizations as { name: string }).name
                : null,
            deleted_at: previousClient.deleted_at,
          }
        : null;

    // ── Send invitation email via Resend ──
    const origin =
      process.env.NEXT_PUBLIC_SITE_URL?.trim() ||
      new URL(request.url).origin;
    const inviteUrl = `${origin}/setup-account?token=${encodeURIComponent(
      inserted.token
    )}`;

    const { subject, text: textBody, html: htmlBody } = buildInvitationEmail({
      inviteUrl,
      orgName,
      ttlDays: INVITE_TTL_DAYS,
    });

    const emailResult = await sendEmail({
      to: email,
      subject,
      text: textBody,
      html: htmlBody,
    });
    if (!emailResult.success) {
      return NextResponse.json(
        {
          error:
            "Invitation enregistree mais l'envoi de l'email a echoue. Le lien peut etre copie manuellement.",
          invite_url: inviteUrl,
        },
        { status: 500 }
      );
    }

    return NextResponse.json({
      ok: true,
      invitation_id: inserted.id,
      ...(softDeleteWarning ?? {}),
    });
  } catch (err) {
    console.error("POST /api/admin/invite error:", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Erreur interne" },
      { status: 500 }
    );
  }
}
