import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { isAdmin } from "@/lib/admin";
import { Resend } from "resend";

export const dynamic = "force-dynamic";

const INVITE_TTL_DAYS = 7;

const resend = new Resend(process.env.RESEND_API_KEY);

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export async function POST(request: Request) {
  try {
    // ── Auth: only admins may send invitations ──
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user || !isAdmin(user.email)) {
      return NextResponse.json({ error: "Acces refuse" }, { status: 403 });
    }

    const body = await request.json().catch(() => null);
    if (!body || typeof body !== "object") {
      return NextResponse.json({ error: "Requete invalide" }, { status: 400 });
    }

    const email =
      typeof body.email === "string" ? body.email.trim().toLowerCase() : "";
    const organizationId =
      typeof body.organization_id === "string"
        ? body.organization_id.trim()
        : "";

    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return NextResponse.json({ error: "Email invalide" }, { status: 400 });
    }

    const admin = createAdminClient();

    // ── Resolve organization ──
    let orgId = organizationId;
    let orgName = typeof body.nom_societe === "string" ? body.nom_societe : "";
    let clientType =
      typeof body.client_type === "string" ? body.client_type : "social";

    if (orgId) {
      // Fetch org for the email template
      const { data: org } = await admin
        .from("organizations")
        .select("id, name, client_type")
        .eq("id", orgId)
        .single();

      if (!org) {
        return NextResponse.json(
          { error: "Organisation introuvable" },
          { status: 400 }
        );
      }
      orgName = org.name;
      clientType = org.client_type;
    } else {
      // Legacy path: create invitation with odoo_partner_id lookup
      const odooPartnerId = Number(body.odoo_partner_id);
      if (!Number.isFinite(odooPartnerId) || odooPartnerId <= 0) {
        return NextResponse.json(
          { error: "organization_id ou odoo_partner_id requis" },
          { status: 400 }
        );
      }

      // Find or fail on organization
      const { data: org } = await admin
        .from("organizations")
        .select("id, name, client_type")
        .eq("odoo_partner_id", odooPartnerId)
        .maybeSingle();

      if (!org) {
        return NextResponse.json(
          {
            error:
              "Aucune organisation trouvee pour cet Odoo Partner ID. Creez d'abord l'organisation.",
          },
          { status: 400 }
        );
      }
      orgId = org.id;
      orgName = org.name;
      clientType = org.client_type;
    }

    // ── Insert invitation (token is auto-generated by DB default) ──
    const expiresAt = new Date(
      Date.now() + INVITE_TTL_DAYS * 24 * 60 * 60 * 1000
    ).toISOString();

    const { data: inserted, error: insertError } = await admin
      .from("invitations")
      .insert({
        email,
        organization_id: orgId,
        client_type: clientType === "agency" ? "agency" : "social",
        expires_at: expiresAt,
        created_by: user.id,
      })
      .select()
      .single();

    if (insertError || !inserted) {
      console.error("[admin/invite] insert failed:", insertError);
      return NextResponse.json(
        {
          error:
            insertError?.message ||
            "Erreur lors de la creation de l'invitation.",
        },
        { status: 500 }
      );
    }

    // ── Send invitation email via Resend ──
    const origin =
      process.env.NEXT_PUBLIC_SITE_URL?.trim() ||
      new URL(request.url).origin;
    const inviteUrl = `${origin}/setup-account?token=${encodeURIComponent(
      inserted.token
    )}`;

    const textBody = `Bonjour,

Vous etes invite(e) a rejoindre le portail Axis Experts pour ${orgName}.
Creez votre compte en cliquant sur ce lien :
${inviteUrl}

Ce lien est valable 7 jours.`;

    const htmlBody = `<div style="font-family: 'Plus Jakarta Sans', system-ui, sans-serif; max-width: 600px; margin: 0 auto;">
<p>Bonjour,</p>
<p>Vous etes invite(e) a rejoindre le portail Axis Experts pour <strong>${escapeHtml(orgName)}</strong>.</p>
<p>Cliquez sur le bouton ci-dessous pour creer votre compte :</p>
<p style="text-align: center; margin: 24px 0;">
  <a href="${escapeHtml(inviteUrl)}" style="background-color: #F5B800; color: #333333; text-decoration: none; padding: 12px 32px; border-radius: 9999px; font-weight: 600; display: inline-block;">
    Creer mon compte
  </a>
</p>
<p style="color: #737373; font-size: 14px;">Ce lien est valable 7 jours.</p>
<p style="color: #737373; font-size: 12px;">Si le bouton ne fonctionne pas, copiez ce lien dans votre navigateur :<br/>
<a href="${escapeHtml(inviteUrl)}" style="color: #F5B800;">${escapeHtml(inviteUrl)}</a></p>
</div>`;

    try {
      await resend.emails.send({
        from: "Axis Experts <noreply@axis-experts.be>",
        to: email,
        subject: `Votre invitation au portail Axis Experts — ${orgName}`,
        text: textBody,
        html: htmlBody,
      });
    } catch (emailErr) {
      console.error("[admin/invite] email send failed:", emailErr);
      return NextResponse.json(
        {
          error:
            "Invitation enregistree mais l'envoi de l'email a echoue. Le lien peut etre copie manuellement.",
          invite_url: inviteUrl,
        },
        { status: 500 }
      );
    }

    return NextResponse.json({ ok: true });
  } catch (err) {
    console.error("POST /api/admin/invite error:", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Erreur interne" },
      { status: 500 }
    );
  }
}
